---
- name: Install Docker
  hosts: "{{ hosts }}"

  vars:
    user: "{{ ansible_user }}"

  tasks:
    - name: Install required packages
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Ubuntu release
      ansible.builtin.shell: "lsb_release -cs"
      register: release

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
        state: present

    - name: Install Docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - python3-docker
        state: latest
        update_cache: true

    - name: Create docker group
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      become: true
      user:
        name: "{{ user }}"
        group: "{{ user }}"
        groups: docker
        append: true

    - name: Set up Docker config
      become: true
      ansible.builtin.copy:
        src: ../../templates/dvpn/daemon.json
        dest: "/etc/docker/daemon.json"

    - name: Reboot server
      become: true
      reboot:
