---
- hosts: "{{ hosts }}"
  pre_tasks:

  - name: Install dependencies
    become: yes
    apt:
      name: unzip
      state: latest
      update_cache: yes

  roles:
    - cloudalchemy.node_exporter
